export const DLH_COURSES = [
  // ─── Design (7 courses) ───
  {
    id: "graphic-design",
    title: "Graphic Design (Beginner–Advanced)",
    category: "Design",
    description: "Master Canva, logo design, flyers, posters, brochures, typography, branding, social media content, and Adobe essentials.",
    image_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400",
    topics: ["Canva Design", "Logo Design", "Flyers & Posters", "Typography & Branding", "Social Media Content", "Adobe Essentials"],
    ai_tutor_prompt: "You are a Graphic Design AI Tutor for DLH. Help students with design concepts, color theory, typography, branding, Canva tips, Adobe tools, and layout best practices.",
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design",
    category: "Design",
    description: "Learn wireframing, prototyping, user-centered design, Figma, XD, and visual hierarchy.",
    image_url: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400",
    topics: ["Wireframing", "Prototyping", "User-Centered Design", "Figma + XD", "Visual Hierarchy"],
    ai_tutor_prompt: "You are a UI/UX Design AI Tutor for DLH. Help students with wireframing, prototyping, user-centered design principles, Figma and XD tools, and visual hierarchy.",
  },
  {
    id: "motion-graphics",
    title: "Motion Graphics & Animation",
    category: "Design",
    description: "Create animated graphics, logo reveals, transitions, kinetic typography, and visual effects using modern tools.",
    image_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400",
    topics: ["Animation Basics", "Kinetic Typography", "Logo Animation", "Transitions & Effects", "After Effects Basics", "Canva Animation"],
    ai_tutor_prompt: "You are a Motion Graphics AI Tutor for DLH. Help students create animations, kinetic typography, logo reveals, and visual effects.",
  },
  {
    id: "brand-identity",
    title: "Brand Identity Design",
    category: "Design",
    description: "Build complete brand identities including logo systems, color palettes, brand guidelines, and visual storytelling.",
    image_url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400",
    topics: ["Logo Systems", "Color Psychology", "Brand Guidelines", "Visual Storytelling", "Brand Strategy", "Packaging Design"],
    ai_tutor_prompt: "You are a Brand Identity Design AI Tutor for DLH. Help students build complete brand identities, logo systems, brand guidelines, and visual storytelling.",
  },
  {
    id: "photo-editing",
    title: "Photo Editing & Retouching",
    category: "Design",
    description: "Master photo editing, retouching, color grading, compositing, and image manipulation with professional tools.",
    image_url: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400",
    topics: ["Photo Retouching", "Color Grading", "Compositing", "Background Removal", "Filters & Presets", "Mobile Editing"],
    ai_tutor_prompt: "You are a Photo Editing AI Tutor for DLH. Help students with photo retouching, color grading, compositing, and professional image editing techniques.",
  },
  {
    id: "print-design",
    title: "Print & Publication Design",
    category: "Design",
    description: "Design professional print materials: business cards, brochures, magazines, banners, and packaging for real-world use.",
    image_url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    topics: ["Business Cards", "Brochures & Flyers", "Magazine Layouts", "Banner Design", "Packaging", "Print-Ready Files"],
    ai_tutor_prompt: "You are a Print Design AI Tutor for DLH. Help students design professional print materials including business cards, brochures, magazines, and packaging.",
  },
  {
    id: "illustration",
    title: "Digital Illustration",
    category: "Design",
    description: "Learn digital drawing, character design, vector illustration, and creating custom artwork for various purposes.",
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400",
    topics: ["Digital Drawing", "Character Design", "Vector Illustration", "Custom Artwork", "Icon Design", "Sticker Design"],
    ai_tutor_prompt: "You are a Digital Illustration AI Tutor for DLH. Help students learn digital drawing, character design, vector illustration, and creating custom artwork.",
  },

  // ─── Development (7 courses) ───
  {
    id: "web-dev-frontend",
    title: "Web Development (Frontend)",
    category: "Development",
    description: "Learn HTML, CSS, JavaScript, responsive design, hosting, and beginner web projects.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["HTML", "CSS", "JavaScript", "Responsive Design", "Hosting", "Beginner Projects"],
    ai_tutor_prompt: "You are a Frontend Web Development AI Tutor for DLH. Help students with HTML, CSS, JavaScript, responsive design, and web hosting.",
  },
  {
    id: "web-dev-fullstack",
    title: "Web Development (Full Stack / Backend)",
    category: "Development",
    description: "Master MERN Stack basics, APIs, databases, and deploying full applications.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["MERN Stack Basics", "APIs", "Databases", "Deploying Full Apps"],
    ai_tutor_prompt: "You are a Full Stack Web Development AI Tutor for DLH. Help students with MERN stack, APIs, databases, backend development, and deploying applications.",
  },
  {
    id: "mobile-app-dev",
    title: "Mobile App Development",
    category: "Development",
    description: "Build mobile applications using React Native, Flutter basics, and cross-platform development fundamentals.",
    image_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    topics: ["React Native", "Flutter Basics", "Cross-Platform Dev", "App Publishing", "UI Components", "Mobile APIs"],
    ai_tutor_prompt: "You are a Mobile App Development AI Tutor for DLH. Help students build mobile applications using React Native and Flutter.",
  },
  {
    id: "python-programming",
    title: "Python Programming",
    category: "Development",
    description: "Learn Python from scratch: syntax, data structures, file handling, automation scripts, and beginner projects.",
    image_url: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400",
    topics: ["Python Basics", "Data Structures", "File Handling", "Automation", "Web Scraping", "Beginner Projects"],
    ai_tutor_prompt: "You are a Python Programming AI Tutor for DLH. Help students learn Python from scratch including syntax, data structures, file handling, and automation.",
  },
  {
    id: "database-management",
    title: "Database Management",
    category: "Development",
    description: "Understand relational databases, SQL queries, NoSQL basics, data modeling, and database design principles.",
    image_url: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400",
    topics: ["SQL Basics", "Database Design", "NoSQL Basics", "Data Modeling", "Query Optimization", "PostgreSQL"],
    ai_tutor_prompt: "You are a Database Management AI Tutor for DLH. Help students learn SQL, database design, NoSQL, and data modeling.",
  },
  {
    id: "wordpress-dev",
    title: "WordPress Development",
    category: "Development",
    description: "Build professional websites with WordPress: themes, plugins, WooCommerce, SEO, and site management.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["WordPress Setup", "Themes & Customization", "Plugins", "WooCommerce", "SEO", "Site Management"],
    ai_tutor_prompt: "You are a WordPress Development AI Tutor for DLH. Help students build professional websites with WordPress including themes, plugins, and WooCommerce.",
  },
  {
    id: "version-control",
    title: "Git & Version Control",
    category: "Development",
    description: "Master Git, GitHub, collaboration workflows, branching strategies, and open-source contributions.",
    image_url: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400",
    topics: ["Git Basics", "GitHub", "Branching", "Pull Requests", "Collaboration", "Open Source"],
    ai_tutor_prompt: "You are a Git & Version Control AI Tutor for DLH. Help students master Git, GitHub, collaboration workflows, and open-source contributions.",
  },

  // ─── Marketing (7 courses) ───
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    category: "Marketing",
    description: "Learn social media strategy, content creation, email marketing, SEO basics, paid ads, branding, and audience growth.",
    image_url: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400",
    topics: ["Social Media Strategy", "Content Creation", "Email Marketing", "SEO Basics", "Paid Ads", "Branding & Audience Growth"],
    ai_tutor_prompt: "You are a Digital Marketing AI Tutor for DLH. Help students with social media strategy, content creation, email marketing, SEO, paid advertising, and brand building.",
  },
  {
    id: "social-media-management",
    title: "Social Media Management",
    category: "Marketing",
    description: "Master scheduling, analytics, community engagement, influencer partnerships, and building brand presence online.",
    image_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400",
    topics: ["Content Scheduling", "Analytics", "Community Engagement", "Influencer Marketing", "Platform Strategy", "Brand Voice"],
    ai_tutor_prompt: "You are a Social Media Management AI Tutor for DLH. Help students manage social media accounts, schedule content, analyze metrics, and grow audiences.",
  },
  {
    id: "seo-mastery",
    title: "SEO & Search Engine Optimization",
    category: "Marketing",
    description: "Deep dive into on-page SEO, off-page SEO, keyword research, link building, and ranking strategies.",
    image_url: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=400",
    topics: ["Keyword Research", "On-Page SEO", "Off-Page SEO", "Link Building", "Technical SEO", "Local SEO"],
    ai_tutor_prompt: "You are an SEO AI Tutor for DLH. Help students with keyword research, on-page SEO, off-page SEO, link building, and ranking strategies.",
  },
  {
    id: "email-marketing",
    title: "Email Marketing & Automation",
    category: "Marketing",
    description: "Build email lists, design campaigns, automate funnels, write compelling copy, and analyze email performance.",
    image_url: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400",
    topics: ["List Building", "Campaign Design", "Automation Funnels", "Copywriting", "A/B Testing", "Analytics"],
    ai_tutor_prompt: "You are an Email Marketing AI Tutor for DLH. Help students build email lists, design campaigns, automate funnels, and analyze performance.",
  },
  {
    id: "copywriting",
    title: "Copywriting & Content Writing",
    category: "Marketing",
    description: "Write persuasive copy for ads, websites, social media, blogs, and marketing campaigns that convert.",
    image_url: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
    topics: ["Ad Copy", "Website Copy", "Blog Writing", "Social Media Copy", "Sales Pages", "Storytelling"],
    ai_tutor_prompt: "You are a Copywriting AI Tutor for DLH. Help students write persuasive copy for ads, websites, social media, and marketing campaigns.",
  },
  {
    id: "paid-advertising",
    title: "Paid Advertising (Google & Facebook Ads)",
    category: "Marketing",
    description: "Run effective paid ad campaigns on Google, Facebook, Instagram, and other platforms to grow businesses.",
    image_url: "https://images.unsplash.com/photo-1553729459-afe8f2e2ed65?w=400",
    topics: ["Google Ads", "Facebook Ads", "Instagram Ads", "Ad Targeting", "Budget Management", "Campaign Optimization"],
    ai_tutor_prompt: "You are a Paid Advertising AI Tutor for DLH. Help students run effective ad campaigns on Google, Facebook, and Instagram.",
  },
  {
    id: "affiliate-marketing",
    title: "Affiliate Marketing",
    category: "Marketing",
    description: "Learn to earn commissions by promoting products, building niche websites, and creating passive income streams.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Affiliate Networks", "Niche Selection", "Content Strategy", "Link Tracking", "Passive Income", "Product Reviews"],
    ai_tutor_prompt: "You are an Affiliate Marketing AI Tutor for DLH. Help students learn affiliate marketing, niche selection, and building passive income streams.",
  },

  // ─── AI & Technology (7 courses) ───
  {
    id: "ai-tools",
    title: "AI Tools for Creators",
    category: "AI & Technology",
    description: "Master ChatGPT, Canva AI, Adobe Firefly, Pictory, RunwayML, image generation, voice tools, and AI automation.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["ChatGPT", "Canva AI", "Adobe Firefly", "Pictory / RunwayML", "Image Generation", "Voice Tools", "AI Automation"],
    ai_tutor_prompt: "You are an AI Tools for Creators Tutor for DLH. Teach students how to use AI tools effectively including ChatGPT prompts, Canva AI, Adobe Firefly, video AI tools, image generation, and AI automation workflows.",
  },
  {
    id: "computer-basics",
    title: "Computer Basics & ICT Skills",
    category: "AI & Technology",
    description: "Learn computer fundamentals, typing, productivity tools, internet safety, file management, and online communication.",
    image_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400",
    topics: ["Computer Fundamentals", "Typing & Productivity", "Internet Safety", "File Management", "Email & Communication"],
    ai_tutor_prompt: "You are a Computer Basics & ICT Skills AI Tutor for DLH. Help students with computer fundamentals, typing skills, productivity tools, internet safety, file management, and email communication.",
  },
  {
    id: "data-analytics",
    title: "Data Analytics & Visualization",
    category: "AI & Technology",
    description: "Analyze data, create dashboards, use Google Sheets, Excel, and visualization tools to make data-driven decisions.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    topics: ["Data Analysis", "Google Sheets", "Excel Advanced", "Dashboards", "Data Visualization", "Reporting"],
    ai_tutor_prompt: "You are a Data Analytics AI Tutor for DLH. Help students analyze data, create dashboards, and make data-driven decisions using spreadsheets and visualization tools.",
  },
  {
    id: "cybersecurity-basics",
    title: "Cybersecurity Fundamentals",
    category: "AI & Technology",
    description: "Understand cybersecurity threats, online safety, password management, privacy, and protecting digital assets.",
    image_url: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400",
    topics: ["Online Safety", "Password Security", "Phishing Prevention", "Data Privacy", "Network Security", "Digital Hygiene"],
    ai_tutor_prompt: "You are a Cybersecurity AI Tutor for DLH. Help students understand cybersecurity threats, online safety, password management, and protecting digital assets.",
  },
  {
    id: "cloud-computing",
    title: "Cloud Computing Basics",
    category: "AI & Technology",
    description: "Introduction to cloud services, Google Workspace, storage solutions, collaboration tools, and cloud-based workflows.",
    image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    topics: ["Cloud Services", "Google Workspace", "Cloud Storage", "Collaboration Tools", "Cloud Security", "SaaS Tools"],
    ai_tutor_prompt: "You are a Cloud Computing AI Tutor for DLH. Help students understand cloud services, Google Workspace, collaboration tools, and cloud-based workflows.",
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    category: "AI & Technology",
    description: "Master the art of writing effective AI prompts for ChatGPT, image generators, and other AI tools to maximize output quality.",
    image_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400",
    topics: ["Prompt Basics", "ChatGPT Prompts", "Image Prompts", "Chain Prompting", "Role Prompting", "Prompt Templates"],
    ai_tutor_prompt: "You are a Prompt Engineering AI Tutor for DLH. Help students write effective prompts for ChatGPT, image generators, and other AI tools.",
  },
  {
    id: "ai-for-business",
    title: "AI for Business Automation",
    category: "AI & Technology",
    description: "Use AI to automate business processes, customer service, content creation, scheduling, and workflow optimization.",
    image_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400",
    topics: ["Business Automation", "AI Customer Service", "Content Automation", "Workflow Tools", "Zapier & Make", "AI Analytics"],
    ai_tutor_prompt: "You are an AI for Business Automation Tutor for DLH. Help students automate business processes using AI tools, Zapier, Make, and workflow optimization.",
  },

  // ─── Creative (7 courses) ───
  {
    id: "content-creation",
    title: "Content Creation & Video Editing",
    category: "Creative",
    description: "Master mobile editing, CapCut, YouTube basics, viral content structure, and AI-assisted editing.",
    image_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400",
    topics: ["Mobile Editing", "CapCut", "YouTube Basics", "Viral Content Structure", "AI-Assisted Editing"],
    ai_tutor_prompt: "You are a Content Creation & Video Editing AI Tutor for DLH. Help students with mobile video editing, CapCut techniques, YouTube channel building, viral content strategies, and AI-assisted editing tools.",
  },
  {
    id: "photography",
    title: "Photography Fundamentals",
    category: "Creative",
    description: "Learn composition, lighting, smartphone photography, product photography, and photo storytelling techniques.",
    image_url: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
    topics: ["Composition", "Lighting", "Smartphone Photography", "Product Photography", "Photo Storytelling", "Editing Basics"],
    ai_tutor_prompt: "You are a Photography AI Tutor for DLH. Help students with composition, lighting, smartphone photography, and photo storytelling techniques.",
  },
  {
    id: "podcasting",
    title: "Podcasting & Audio Production",
    category: "Creative",
    description: "Start and grow a podcast: recording, editing, publishing, guest interviews, and monetization strategies.",
    image_url: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400",
    topics: ["Podcast Setup", "Audio Recording", "Editing & Mixing", "Publishing", "Guest Interviews", "Monetization"],
    ai_tutor_prompt: "You are a Podcasting AI Tutor for DLH. Help students start and grow podcasts, record quality audio, edit episodes, and monetize their shows.",
  },
  {
    id: "youtube-mastery",
    title: "YouTube Channel Mastery",
    category: "Creative",
    description: "Build and grow a YouTube channel: thumbnails, SEO, scripting, filming, editing, and audience engagement.",
    image_url: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400",
    topics: ["Channel Setup", "Thumbnails", "YouTube SEO", "Scripting", "Filming Tips", "Audience Growth"],
    ai_tutor_prompt: "You are a YouTube Mastery AI Tutor for DLH. Help students build and grow YouTube channels with thumbnails, SEO, scripting, and audience engagement.",
  },
  {
    id: "blogging",
    title: "Blogging & Written Content",
    category: "Creative",
    description: "Start a blog, write engaging articles, optimize for SEO, build an audience, and monetize your writing.",
    image_url: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400",
    topics: ["Blog Setup", "Article Writing", "SEO Writing", "Audience Building", "Monetization", "Content Planning"],
    ai_tutor_prompt: "You are a Blogging AI Tutor for DLH. Help students start blogs, write engaging content, optimize for SEO, and monetize their writing.",
  },
  {
    id: "social-media-content",
    title: "Social Media Content Creation",
    category: "Creative",
    description: "Create stunning social media content: reels, stories, carousels, infographics, and platform-specific strategies.",
    image_url: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400",
    topics: ["Reels & Shorts", "Stories", "Carousels", "Infographics", "Platform Strategy", "Content Calendar"],
    ai_tutor_prompt: "You are a Social Media Content Creation AI Tutor for DLH. Help students create stunning reels, stories, carousels, and platform-specific content.",
  },
  {
    id: "streaming",
    title: "Live Streaming & Webinars",
    category: "Creative",
    description: "Set up and run professional live streams, webinars, and virtual events using OBS, Zoom, and social platforms.",
    image_url: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400",
    topics: ["OBS Setup", "Zoom Webinars", "Live on Social Media", "Audience Interaction", "Stream Quality", "Virtual Events"],
    ai_tutor_prompt: "You are a Live Streaming AI Tutor for DLH. Help students set up and run professional live streams, webinars, and virtual events.",
  },

  // ─── Business (7 courses) ───
  {
    id: "tech-entrepreneurship",
    title: "Tech Entrepreneurship",
    category: "Business",
    description: "Learn to monetize digital skills, build your brand, develop business strategies, and sell digital services.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    topics: ["Monetizing Digital Skills", "Brand Building", "Business Strategy", "Selling Digital Services"],
    ai_tutor_prompt: "You are a Tech Entrepreneurship AI Tutor for DLH. Help students monetize their digital skills, build personal brands, develop business strategies, and learn how to sell digital services online.",
  },
  {
    id: "freelancing",
    title: "Freelancing & Remote Work",
    category: "Business",
    description: "Start freelancing on Upwork, Fiverr, and other platforms. Learn pricing, proposals, client management, and time tracking.",
    image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400",
    topics: ["Freelance Platforms", "Pricing Strategy", "Writing Proposals", "Client Management", "Time Tracking", "Portfolio Building"],
    ai_tutor_prompt: "You are a Freelancing AI Tutor for DLH. Help students start freelancing, write proposals, manage clients, and build profitable freelance careers.",
  },
  {
    id: "ecommerce",
    title: "E-Commerce & Online Selling",
    category: "Business",
    description: "Set up online stores, sell products digitally, learn about payment gateways, logistics, and customer service.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    topics: ["Online Store Setup", "Product Listings", "Payment Gateways", "Logistics", "Customer Service", "Sales Strategies"],
    ai_tutor_prompt: "You are an E-Commerce AI Tutor for DLH. Help students set up online stores, sell products, manage payments, and grow their e-commerce businesses.",
  },
  {
    id: "personal-branding",
    title: "Personal Branding",
    category: "Business",
    description: "Build a powerful personal brand online: LinkedIn optimization, portfolio creation, networking, and thought leadership.",
    image_url: "https://images.unsplash.com/photo-1560472355-536de3962603?w=400",
    topics: ["LinkedIn Optimization", "Portfolio Building", "Networking", "Thought Leadership", "Online Presence", "Brand Consistency"],
    ai_tutor_prompt: "You are a Personal Branding AI Tutor for DLH. Help students build powerful personal brands, optimize LinkedIn, create portfolios, and establish thought leadership.",
  },
  {
    id: "project-management",
    title: "Project Management",
    category: "Business",
    description: "Learn project planning, task management, Agile basics, team collaboration, and using tools like Trello and Asana.",
    image_url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400",
    topics: ["Project Planning", "Task Management", "Agile Basics", "Trello & Asana", "Team Collaboration", "Time Management"],
    ai_tutor_prompt: "You are a Project Management AI Tutor for DLH. Help students with project planning, task management, Agile methodologies, and collaboration tools.",
  },
  {
    id: "financial-literacy",
    title: "Financial Literacy for Creators",
    category: "Business",
    description: "Understand budgeting, invoicing, taxes for freelancers, savings strategies, and financial planning for digital careers.",
    image_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400",
    topics: ["Budgeting", "Invoicing", "Freelancer Taxes", "Savings Strategies", "Financial Planning", "Mobile Money"],
    ai_tutor_prompt: "You are a Financial Literacy AI Tutor for DLH. Help students understand budgeting, invoicing, taxes, and financial planning for digital careers in Sierra Leone.",
  },
  {
    id: "digital-product-creation",
    title: "Digital Product Creation",
    category: "Business",
    description: "Create and sell digital products: templates, eBooks, courses, printables, and digital downloads for passive income.",
    image_url: "https://images.unsplash.com/photo-1553484771-371a605b060b?w=400",
    topics: ["Template Design", "eBook Creation", "Online Courses", "Printables", "Digital Downloads", "Passive Income"],
    ai_tutor_prompt: "You are a Digital Product Creation AI Tutor for DLH. Help students create and sell digital products including templates, eBooks, courses, and printables.",
  },

  // ─── Microsoft Office (7 courses) ───
  {
    id: "ms-word",
    title: "Microsoft Word Mastery",
    category: "Microsoft Office",
    description: "Master document creation, formatting, tables, headers, mail merge, templates, and professional report writing.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["Document Formatting", "Tables & Charts", "Headers & Footers", "Mail Merge", "Templates", "Report Writing"],
    ai_tutor_prompt: "You are a Microsoft Word AI Tutor for DLH. Help students master document creation, formatting, tables, mail merge, and professional report writing. Use Sierra Leonean examples like writing official letters, school reports, and business documents.",
  },
  {
    id: "ms-excel",
    title: "Microsoft Excel Mastery",
    category: "Microsoft Office",
    description: "Learn spreadsheets, formulas, pivot tables, charts, data analysis, VLOOKUP, and financial modeling in Excel.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Formulas & Functions", "Pivot Tables", "Charts & Graphs", "Data Analysis", "VLOOKUP & HLOOKUP", "Financial Modeling"],
    ai_tutor_prompt: "You are a Microsoft Excel AI Tutor for DLH. Help students learn formulas, pivot tables, charts, data analysis, and financial modeling. Use examples like tracking business expenses in Freetown or analyzing school enrollment data.",
  },
  {
    id: "ms-powerpoint",
    title: "Microsoft PowerPoint Mastery",
    category: "Microsoft Office",
    description: "Create stunning presentations with animations, slide design, storytelling, templates, and professional delivery tips.",
    image_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400",
    topics: ["Slide Design", "Animations & Transitions", "Storytelling", "Templates", "Presenter Mode", "Professional Tips"],
    ai_tutor_prompt: "You are a Microsoft PowerPoint AI Tutor for DLH. Help students create stunning presentations with animations, storytelling, and professional delivery techniques.",
  },
  {
    id: "ms-outlook",
    title: "Microsoft Outlook & Email Management",
    category: "Microsoft Office",
    description: "Master professional email communication, calendar management, task tracking, and contact organization with Outlook.",
    image_url: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400",
    topics: ["Email Etiquette", "Calendar Management", "Task Tracking", "Contact Organization", "Rules & Filters", "Meeting Scheduling"],
    ai_tutor_prompt: "You are a Microsoft Outlook AI Tutor for DLH. Help students master professional email communication, calendar management, and productivity with Outlook.",
  },
  {
    id: "ms-access",
    title: "Microsoft Access & Database Basics",
    category: "Microsoft Office",
    description: "Build and manage databases, create forms, queries, reports, and data entry systems using Microsoft Access.",
    image_url: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400",
    topics: ["Database Design", "Forms", "Queries", "Reports", "Data Entry", "Relationships"],
    ai_tutor_prompt: "You are a Microsoft Access AI Tutor for DLH. Help students build databases, create forms, write queries, and generate reports using Microsoft Access.",
  },
  {
    id: "ms-onenote",
    title: "Microsoft OneNote & Note-Taking",
    category: "Microsoft Office",
    description: "Organize notes, study materials, research, and projects using Microsoft OneNote for academic and professional use.",
    image_url: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400",
    topics: ["Note Organization", "Notebooks & Sections", "Tags & Search", "Audio Notes", "Collaboration", "Study Templates"],
    ai_tutor_prompt: "You are a Microsoft OneNote AI Tutor for DLH. Help students organize notes, study materials, and projects using OneNote for academic and professional productivity.",
  },
  {
    id: "ms-teams",
    title: "Microsoft Teams & Collaboration",
    category: "Microsoft Office",
    description: "Master virtual meetings, team collaboration, file sharing, channels, and productivity workflows with Microsoft Teams.",
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400",
    topics: ["Virtual Meetings", "Channels & Chats", "File Sharing", "Screen Sharing", "Breakout Rooms", "Integration Apps"],
    ai_tutor_prompt: "You are a Microsoft Teams AI Tutor for DLH. Help students master virtual meetings, team collaboration, file sharing, and productivity workflows with Microsoft Teams.",
  },
];

export const COURSE_CATEGORIES = ["All", ...Array.from(new Set(DLH_COURSES.map(c => c.category)))];
