export const DLH_COURSES = [
  {
    id: "graphic-design",
    title: "Graphic Design (Beginner–Advanced)",
    category: "Design",
    description: "Master Canva, logo design, flyers, posters, brochures, typography, branding, social media content, and Adobe essentials.",
    image_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400",
    topics: ["Canva Design", "Logo Design", "Flyers & Posters", "Typography & Branding", "Social Media Content", "Adobe Essentials"],
    ai_tutor_prompt: "You are a Graphic Design AI Tutor for DLH. Help students with design concepts, color theory, typography, branding, Canva tips, Adobe tools, and layout best practices. Generate design ideas, suggest color palettes, create sample layouts, and review assignments.",
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    category: "Marketing",
    description: "Learn social media strategy, content creation, email marketing, SEO basics, paid ads, branding, and audience growth.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    topics: ["Social Media Strategy", "Content Creation", "Email Marketing", "SEO Basics", "Paid Ads", "Branding & Audience Growth"],
    ai_tutor_prompt: "You are a Digital Marketing AI Tutor for DLH. Help students with social media strategy, content creation, email marketing, SEO, paid advertising, and brand building. Write captions, create marketing strategies, suggest hashtags, and build content calendars.",
  },
  {
    id: "ai-tools",
    title: "AI Tools for Creators",
    category: "AI & Technology",
    description: "Master ChatGPT, Canva AI, Adobe Firefly, Pictory, RunwayML, image generation, voice tools, and AI automation.",
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    topics: ["ChatGPT", "Canva AI", "Adobe Firefly", "Pictory / RunwayML", "Image Generation", "Voice Tools", "AI Automation"],
    ai_tutor_prompt: "You are an AI Tools for Creators Tutor for DLH. Teach students how to use AI tools effectively including ChatGPT prompts, Canva AI, Adobe Firefly, video AI tools, image generation, and AI automation workflows.",
  },
  {
    id: "web-dev-frontend",
    title: "Web Development (Frontend)",
    category: "Development",
    description: "Learn HTML, CSS, JavaScript, responsive design, hosting, and beginner web projects.",
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    topics: ["HTML", "CSS", "JavaScript", "Responsive Design", "Hosting", "Beginner Projects"],
    ai_tutor_prompt: "You are a Frontend Web Development AI Tutor for DLH. Help students with HTML, CSS, JavaScript, responsive design, and web hosting. Fix code, explain errors, generate components, and suggest improvements.",
  },
  {
    id: "web-dev-fullstack",
    title: "Web Development (Full Stack / Backend)",
    category: "Development",
    description: "Master MERN Stack basics, APIs, databases, and deploying full applications.",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    topics: ["MERN Stack Basics", "APIs", "Databases", "Deploying Full Apps"],
    ai_tutor_prompt: "You are a Full Stack Web Development AI Tutor for DLH. Help students with MERN stack, APIs, databases, backend development, and deploying applications. Fix code, explain architecture, and guide project building.",
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design",
    category: "Design",
    description: "Learn wireframing, prototyping, user-centered design, Figma, XD, and visual hierarchy.",
    image_url: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400",
    topics: ["Wireframing", "Prototyping", "User-Centered Design", "Figma + XD", "Visual Hierarchy"],
    ai_tutor_prompt: "You are a UI/UX Design AI Tutor for DLH. Help students with wireframing, prototyping, user-centered design principles, Figma and XD tools, and visual hierarchy. Generate wireframes, give UX feedback, and suggest better layouts.",
  },
  {
    id: "computer-basics",
    title: "Computer Basics & ICT Skills",
    category: "Technology",
    description: "Learn computer fundamentals, typing, productivity tools, internet safety, file management, and online communication.",
    image_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400",
    topics: ["Computer Fundamentals", "Typing & Productivity", "Internet Safety", "File Management", "Email & Communication"],
    ai_tutor_prompt: "You are a Computer Basics & ICT Skills AI Tutor for DLH. Help students with computer fundamentals, typing skills, productivity tools, internet safety, file management, and email communication.",
  },
  {
    id: "content-creation",
    title: "Content Creation & Video Editing",
    category: "Creative",
    description: "Master mobile editing, CapCut, YouTube basics, viral content structure, and AI-assisted editing.",
    image_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400",
    topics: ["Mobile Editing", "CapCut", "YouTube Basics", "Viral Content Structure", "AI-Assisted Editing"],
    ai_tutor_prompt: "You are a Content Creation & Video Editing AI Tutor for DLH. Help students with mobile video editing, CapCut techniques, YouTube channel building, viral content strategies, and AI-assisted editing tools.",
  },
  {
    id: "tech-entrepreneurship",
    title: "Tech Entrepreneurship",
    category: "Business",
    description: "Learn to monetize digital skills, build your brand, develop business strategies, and sell digital services.",
    image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    topics: ["Monetizing Digital Skills", "Brand Building", "Business Strategy", "Selling Digital Services"],
    ai_tutor_prompt: "You are a Tech Entrepreneurship AI Tutor for DLH. Help students monetize their digital skills, build personal brands, develop business strategies, and learn how to sell digital services online.",
  },
];

export const COURSE_CATEGORIES = ["All", ...Array.from(new Set(DLH_COURSES.map(c => c.category)))];
